version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bi_products_prices_backend
    container_name: bi_products_prices_backend
    command: /bin/sh /shell/entrypoint.sh
    volumes:
      - ./backend/source:/project
      - ./backend/shell/entrypoint.sh:/shell/entrypoint.sh
      - static_volume:/project/staticfiles
    ports:
      - "${DJANGO_EXTERNAL_PORT}:${DJANGO_INTERNAL_PORT}"
    expose:
      - 8000
    environment:
      DJANGO_DATABASE: "${DJANGO_DATABASE}"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      DJANGO_INTERNAL_PORT: "${DJANGO_INTERNAL_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - project_db
    # Required on dev to allow pdb on a running container
    stdin_open: true
    tty: true

  project_db:
      image: postgres:13.0-alpine
      container_name: bi_products_prices_db
      restart: always
      volumes:
        - postgres_db_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_HOST: "${POSTGRES_HOST}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

      ports:
        - "5432:5432"

volumes:
    postgres_db_data:
    static_volume:
