version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh /project/entrypoint.sh
    volumes:
      - ./backend/source/app:/project
      - ./backend/shell/entrypoint.sh:/project/entrypoint.sh
      - static_volume:/project/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    #    env_file:
    #      - ../.env
    depends_on:
      - db

  nginx:
      build: ./nginx
      ports:
        - "${HOST_DEFAULT_PORT}:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./nginx/backend.local:/etc/nginx/sites-enabled/backend.local
        - static_volume:/project/staticfiles
    #    depends_on:
    #      - backend

  db:
      image: postgres:13.0-alpine
      volumes:
        - ./postgres_data:/var/lib/postgresql/data/
#        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=app_user
        - POSTGRES_PASSWORD=app_pwd
        - POSTGRES_DB=django_app_dev
      ports:
        - "5432:5432"

volumes:
    postgres_data:
    static_volume:
